import { isSimulationUrlAllowed } from '@/lib/simulation';
import { demoExams, demoQuestions, demoStudents, demoTeachers } from '@/lib/demo-data';
import type { ExamApi } from './exam-api';
import type {
  AdminExamInput, AdminQuestionInput, AdminResultRow, AdminStudentInput, AdminUserInput, DashboardStats, ImportStudentRow, ImportStudentsResult,
  AttemptControl, ExamRecord, ExamResult, ExamSummary, MonitoringRow, Question, QuestionRecord, QuestionPackageSummary,
  ResumeAttemptResponse, SaveAnswersResponse, Session, StartExamResponse, StudentRecord,
  SubmitResponse, TeacherInput, TeacherRecord, UploadImageResponse, User, ValidationAssignment,
} from './types';

const delay = (ms = 150) => new Promise((resolve) => setTimeout(resolve, ms));
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value));
const uid = (prefix: string) => `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
const parseCsvLine=(line:string)=>{const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){out.push(cur);cur='';}else cur+=ch;}out.push(cur);return out;};
const plainText=(html:string)=>html.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const parseInteractionData=(value:unknown)=>{if(!value)return null;try{const parsed=typeof value==='string'?JSON.parse(value):value as any; if(parsed&&Array.isArray(parsed.left)&&Array.isArray(parsed.right)) return {left:parsed.left.map((item:any,idx:number)=>({id:String(item?.id||`L${idx+1}`),text:String(item?.text||'')})),right:parsed.right.map((item:any,idx:number)=>({id:String(item?.id||`R${idx+1}`),text:String(item?.text||'')}))};}catch{}return null;};
const parseMatchingKey=(value:string)=>{const out:Record<string,string>={};String(value||'').split('|').map(x=>x.trim()).filter(Boolean).forEach((pair)=>{const [left,right]=pair.split(':').map((item)=>Number(item));if(left&&right)out[`L${left}`]=`R${right}`;});return out;};
const parseMatchingAnswer=(value:string)=>{try{const parsed=JSON.parse(String(value||'{}'));return parsed&&typeof parsed==='object'?parsed as Record<string,string>:{};}catch{return {};}};

type Manager = Extract<User['role'], 'super_admin' | 'teacher'>;
interface DemoAttemptState {
  attemptId: string; examId: string; studentId: string; startedAt: string; expiresAt: string;
  revision: number; status: 'IN_PROGRESS' | 'PAUSED' | 'SUBMITTED' | 'EXPIRED'; questionOrder: string[];
  optionOrders: Record<string, string[]>; answers: Record<string, string>; submittedAt?: string; focusViolationCount?: number; pauseStartedAt?: string; lastWarning?: string; lastWarningAt?: string;
}

const SUPER_ADMIN: User = { userId: 'SA-001', name: 'Super Admin SuKa Olimpiade Fisika', username: 'superadmin', role: 'super_admin', status: 'ACTIVE' };
const VALIDATOR: User = { userId: 'V-001', name: 'Dr. Rina Validator, M.Si.', username: 'validator', role: 'validator', status: 'ACTIVE', subject: 'Fisika' };
const store = {
  exams: clone(demoExams), questions: clone(demoQuestions), students: clone(demoStudents), teachers: clone(demoTeachers), validators: [VALIDATOR],
  examMappings: Object.fromEntries(demoExams.map((exam)=>[exam.examId,demoQuestions.filter((q)=>q.examId===exam.examId).map((q)=>q.questionId)])) as Record<string,string[]>,
  attempts: [] as DemoAttemptState[], submissions: [] as AdminResultRow[], validations: {} as Record<string,{status:string;note:string;updatedAt:string}>, assignments: [] as ValidationAssignment[],
};
const DEMO_STORE_KEY = 'suka-olimpiade-fisika.demo-store.v2';
let hydrated = false;
function hydrate() {
  if (hydrated || typeof window === 'undefined') return; hydrated = true;
  store.validations = store.validations || {}; store.validators = store.validators || [VALIDATOR]; store.assignments = (!Array.isArray(store.assignments) || store.assignments.length===0) ? demoQuestions.map(q => ({assignmentId:`AS-${q.questionId}-V-001`,questionId:q.questionId,questionCode:q.code,questionText:q.questionText,validatorId:'V-001',validatorName:VALIDATOR.name,status:'PENDING',authorId:q.authorId,authorName:q.authorName})) : store.assignments;
  try {
    const raw = localStorage.getItem(DEMO_STORE_KEY); if (!raw) return; const saved = JSON.parse(raw);
    for (const key of ['exams','questions','students','teachers','validators','attempts','submissions'] as const) if (Array.isArray(saved[key])) (store as any)[key] = saved[key]; if(saved.validations && typeof saved.validations==='object') store.validations=saved.validations; if(Array.isArray(saved.assignments)) store.assignments=saved.assignments; if(saved.examMappings && typeof saved.examMappings==='object') store.examMappings=saved.examMappings;
  } catch { /* demo uses seed */ }
}
function persist() { if (typeof window !== 'undefined') try { localStorage.setItem(DEMO_STORE_KEY, JSON.stringify(store)); } catch {} }
function sessionFor(user: User): Session { return { token: `demo:${user.role}:${user.userId}`, user, expiresAt: new Date(Date.now() + 12 * 3600_000).toISOString() }; }
function userFromToken(token: string): User {
  if (!token?.startsWith('demo:')) throw new Error('Sesi demo tidak valid.');
  const [, role, userId] = token.split(':');
  if (role === 'super_admin') return SUPER_ADMIN;
  if (role === 'teacher') return store.teachers.find((t) => t.userId === userId) || store.teachers[0];
  if (role === 'validator') return VALIDATOR;
  return store.students.find((s) => s.userId === userId) || store.students[0];
}
function requireManager(user: User): asserts user is User & { role: Manager } { if (user.role === 'student') throw new Error('Anda tidak memiliki izin.'); }
function visibleExams(user: User) { return user.role === 'teacher' ? store.exams.filter((e) => e.ownerId === user.userId) : store.exams; }
function canManageExam(user: User, examId: string) { const exam = store.exams.find((e) => e.examId === examId); return !!exam && (user.role === 'super_admin' || (user.role === 'teacher' && exam.ownerId === user.userId)); }
function teacherName(id?: string) { return store.teachers.find((t) => t.userId === id)?.name || ''; }
function shuffled<T>(items: T[]) { const arr=[...items]; for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];} return arr; }
function publicQuestion(record: QuestionRecord, number: number, order?: string[]): Question {
  const interactionData=parseInteractionData((record as any).interactionData);
  const opts = { A: record.optionA, B: record.optionB, C: record.optionC, D: record.optionD, E: record.optionE || '' } as Record<string,string>;
  const keys=(order || ['A','B','C','D','E']).filter((key)=>Boolean(opts[key]));
  return { questionId: record.questionId, number, text: record.questionText, questionHtml: record.questionHtml || record.questionText, questionType: record.questionType, scoringMode: record.scoringMode, maxScore: record.maxScore || record.score || 1, options: record.questionType==='MATCHING'?[]:keys.map((key)=>({key,label:opts[key]})), interactionData, imageUrl: record.imageUrl || null, imageFileId: record.imageFileId || null, simulationEnabled: Boolean(record.simulationEnabled && record.simulationUrl), simulationUrl: record.simulationUrl || '', simulationTitle: record.simulationTitle || '', simulationDescription: record.simulationDescription || '', simulationAspectRatio: record.simulationAspectRatio || '16/9', difficulty: record.difficulty, tag: record.tag };
}
function examQuestions(examId: string) { const ids=store.examMappings[examId]||store.questions.filter((q)=>q.examId===examId).map((q)=>q.questionId); return ids.map((id)=>store.questions.find((q)=>q.questionId===id)).filter((q):q is QuestionRecord=>Boolean(q&&q.status==='PUBLISHED')); }
function attemptQuestions(a: DemoAttemptState, offset:number, limit:number) { return a.questionOrder.slice(offset,offset+limit).map((id)=>store.questions.find((q)=>q.questionId===id)).filter(Boolean).map((q,idx)=>publicQuestion(q as QuestionRecord,offset+idx+1,a.optionOrders[(q as QuestionRecord).questionId])); }
function summary(exam: ExamRecord, studentId?: string): ExamSummary { const a=studentId?store.attempts.find((x)=>x.studentId===studentId&&x.examId===exam.examId):undefined; const s=a?store.submissions.find((x)=>x.attemptId===a.attemptId):undefined; return {...exam,tokenRequired:Boolean(exam.token),attemptStatus:a?.status,attemptId:a?.attemptId,score:s?.score??null}; }

export class DemoExamApi implements ExamApi {
  constructor(){hydrate();}
  async login(username:string,password:string){await delay(); if(username==='superadmin'&&password==='super123') return sessionFor(SUPER_ADMIN); if(username==='panitia'&&password==='panitia123') return sessionFor(store.teachers[0]); if(username==='validator'&&password==='validator123') return sessionFor(VALIDATOR); if(username==='panitiabio'&&password==='panitia123') return sessionFor(store.teachers[1]); if(username==='peserta'&&password==='peserta123') return sessionFor(store.students[0]); const st=store.students.find((s)=>s.username===username); if(st&&password==='peserta123') return sessionFor(st); throw new Error('Username atau password salah.');}
  async logout(){await delay(50);} async getSession(token:string){await delay(50);return sessionFor(userFromToken(token));}
  async getAvailableExams(token:string){await delay();const u=userFromToken(token);if(u.role!=='student')throw new Error('Hanya peserta.');return store.exams.filter((e)=>e.className===u.className).map((e)=>summary(e,u.userId));}
  async startExam(token:string,examId:string,examToken?:string):Promise<StartExamResponse>{await delay(220);const u=userFromToken(token);if(u.role!=='student')throw new Error('Hanya peserta yang dapat memulai ujian.');const exam=store.exams.find((e)=>e.examId===examId);if(!exam)throw new Error('Ujian tidak ditemukan.');if(exam.token&&exam.token!==examToken)throw new Error('Token ujian tidak sesuai.');const existing=store.attempts.find((a)=>a.studentId===u.userId&&a.examId===examId);if(existing && ['IN_PROGRESS','PAUSED'].includes(existing.status)){const r=await this.resumeAttempt(token,existing.attemptId,0,10);return{attempt:r.attempt,initialQuestions:r.questions,offset:r.offset,hasMore:r.hasMore};}if(existing?.status==='SUBMITTED')throw new Error('Ujian sudah dikumpulkan.');const qs=examQuestions(examId).slice(0,exam.questionCount||undefined);const order=exam.randomizeQuestion?shuffled(qs.map((q)=>q.questionId)):qs.map((q)=>q.questionId);const optionOrders:Record<string,string[]>={};qs.forEach((q)=>{const keys=(['A','B','C','D','E'] as const).filter((key)=>Boolean((q as unknown as Record<string,unknown>)[`option${key}`]));optionOrders[q.questionId]=q.questionType==='TRUE_FALSE'||q.questionType==='MATCHING'?keys:[...(exam.randomizeOption?shuffled(keys):keys)];});const started=new Date();const expires=new Date(Math.min(started.getTime()+exam.durationMinutes*60_000,new Date(exam.endTime).getTime())).toISOString();const a:DemoAttemptState={attemptId:uid('ATT'),examId,studentId:u.userId,startedAt:started.toISOString(),expiresAt:expires,revision:0,status:'IN_PROGRESS',questionOrder:order,optionOrders,answers:{},focusViolationCount:0,pauseStartedAt:'',lastWarning:'',lastWarningAt:''};store.attempts.push(a);persist();return{attempt:{attemptId:a.attemptId,examId,studentId:u.userId,startedAt:a.startedAt,expiresAt:a.expiresAt,serverTime:new Date().toISOString(),revision:0,status:'IN_PROGRESS',questionCount:order.length,batchSize:10,exam},initialQuestions:attemptQuestions(a,0,10),offset:0,hasMore:order.length>10};}
  async resumeAttempt(token:string,attemptId:string,offset=0,limit=10):Promise<ResumeAttemptResponse>{await delay();const u=userFromToken(token);const a=store.attempts.find((x)=>x.attemptId===attemptId&&x.studentId===u.userId);if(!a)throw new Error('Attempt tidak ditemukan.');const exam=store.exams.find((e)=>e.examId===a.examId)!;return{attempt:{attemptId:a.attemptId,examId:a.examId,studentId:a.studentId,startedAt:a.startedAt,expiresAt:a.expiresAt,serverTime:new Date().toISOString(),revision:a.revision,status:a.status,questionCount:a.questionOrder.length,batchSize:limit,exam},answers:clone(a.answers),questions:attemptQuestions(a,offset,limit),offset,hasMore:offset+limit<a.questionOrder.length};}
  async getQuestionsBatch(token:string,attemptId:string,offset:number,limit:number){await delay();const u=userFromToken(token);const a=store.attempts.find((x)=>x.attemptId===attemptId&&x.studentId===u.userId);if(!a)throw new Error('Attempt tidak ditemukan.');return{questions:attemptQuestions(a,offset,limit),offset,hasMore:offset+limit<a.questionOrder.length};}
  async saveAnswers(token:string,attemptId:string,revision:number,answers:Record<string,string>):Promise<SaveAnswersResponse>{await delay(90);const u=userFromToken(token);const a=store.attempts.find((x)=>x.attemptId===attemptId&&x.studentId===u.userId);if(!a||a.status!=='IN_PROGRESS')throw new Error('Attempt tidak aktif.');a.answers={...a.answers,...answers};a.revision=Math.max(a.revision+1,revision);persist();return{attemptId,revision:a.revision,lastSyncAt:new Date().toISOString()};}
  async submitExam(token:string,input:{attemptId:string;submissionId:string;revision:number;answers:Record<string,string>}):Promise<SubmitResponse>{await delay(250);const u=userFromToken(token);const a=store.attempts.find((x)=>x.attemptId===input.attemptId&&x.studentId===u.userId);if(!a)throw new Error('Attempt tidak ditemukan.');const existing=store.submissions.find((s)=>s.attemptId===a.attemptId);if(existing)return{submissionId:existing.submissionId,attemptId:a.attemptId,accepted:true,alreadySubmitted:true,submittedAt:existing.submittedAt,result:await this.getResult(token,a.attemptId)};a.answers={...a.answers,...input.answers};let correct=0,wrong=0,blank=0,points=0,max=0;a.questionOrder.forEach((id)=>{const q=store.questions.find((x)=>x.questionId===id);if(!q)return;const weight=Number(q.maxScore||q.score||1);max+=weight;if(q.questionType==='MATCHING'){const expected=parseMatchingKey(String(q.correctAnswers||q.correctAnswer||''));const answerMap=parseMatchingAnswer(String(a.answers[id]||''));const leftItems=parseInteractionData((q as any).interactionData)?.left||[];const answeredValues=Object.values(answerMap).filter(Boolean);if(!answeredValues.length){blank++;return;}const total=Math.max(Object.keys(expected).length,leftItems.length,1);const hits=Object.keys(expected).filter((leftId)=>answerMap[leftId]===expected[leftId]).length;const exact=hits===Object.keys(expected).length&&Object.keys(answerMap).length>=Object.keys(expected).length; if(exact){correct++;points+=weight;return;} wrong++; if(q.scoringMode==='PARTIAL_NO_PENALTY'&&total){points+=weight*(hits/total);} return;} const ans=String(a.answers[id]||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);const key=String(q.correctAnswers||q.correctAnswer||'').split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);if(!ans.length){blank++;return;}const exact=ans.length===key.length&&(q.questionType==='TRUE_FALSE'?ans.join('|')===key.join('|'):[...ans].sort().join('|')===[...key].sort().join('|'));if(exact){correct++;points+=weight;return;}wrong++;if(q.scoringMode==='PARTIAL_NO_PENALTY'&&key.length){const hits=q.questionType==='TRUE_FALSE'?key.filter((value,index)=>ans[index]===value).length:ans.filter(x=>key.includes(x)).length;points+=weight*(hits/key.length);}});const score=max?Math.round(points/max*10000)/100:0;const submittedAt=new Date().toISOString();const exam=store.exams.find((e)=>e.examId===a.examId)!;store.submissions.push({submissionId:input.submissionId,attemptId:a.attemptId,studentId:u.userId,studentName:u.name,className:u.className||'-',examId:a.examId,examTitle:exam.title,score,correctCount:correct,wrongCount:wrong,blankCount:blank,submittedAt});a.status='SUBMITTED';a.submittedAt=submittedAt;persist();return{submissionId:input.submissionId,attemptId:a.attemptId,accepted:true,submittedAt,result:await this.getResult(token,a.attemptId)};}
  async getResult(token:string,attemptId:string):Promise<ExamResult|null>{await delay(60);const u=userFromToken(token);const a=store.attempts.find((x)=>x.attemptId===attemptId);if(!a)return null;const exam=store.exams.find((e)=>e.examId===a.examId)!;const allowed=u.role==='student'?a.studentId===u.userId:(u.role==='super_admin'||exam.ownerId===u.userId);if(!allowed)return null;const sub=store.submissions.find((s)=>s.attemptId===attemptId);if(!sub)return null;const visible=u.role!=='student'||exam.resultVisibility==='immediate'||(exam.resultVisibility==='after_exam_closed'&&Date.now()>new Date(exam.endTime).getTime());return{examId:exam.examId,attemptId,title:exam.title,subject:exam.subject,score:sub.score,correctCount:sub.correctCount,wrongCount:sub.wrongCount,blankCount:sub.blankCount,questionCount:sub.correctCount+sub.wrongCount+sub.blankCount,submittedAt:sub.submittedAt,visible};}
  async getMyResults(token:string){const u=userFromToken(token);const results=await Promise.all(store.attempts.filter((a)=>a.studentId===u.userId&&a.status==='SUBMITTED').map((a)=>this.getResult(token,a.attemptId)));return results.filter(Boolean) as ExamResult[];}
  async getDashboardStats(token:string):Promise<DashboardStats>{await delay();const u=userFromToken(token);requireManager(u);const exams=visibleExams(u);const ids=new Set(exams.map((e)=>e.examId));const attempts=store.attempts.filter((a)=>ids.has(a.examId));const now=Date.now();return{activeExams:exams.filter((e)=>new Date(e.startTime).getTime()<=now&&new Date(e.endTime).getTime()>=now).length,upcomingExams:exams.filter((e)=>new Date(e.startTime).getTime()>now).length,students:store.students.length,inProgress:attempts.filter((a)=>a.status==='IN_PROGRESS').length,submitted:attempts.filter((a)=>a.status==='SUBMITTED').length,notSubmitted:Math.max(0,store.students.length-attempts.filter((a)=>a.status==='SUBMITTED').length)};}
  async listExams(token:string){await delay();const u=userFromToken(token);requireManager(u);return clone(visibleExams(u));}
  async saveExam(token:string,input:AdminExamInput){await delay();const u=userFromToken(token);requireManager(u);const id=input.examId||uid('EX');const existing=store.exams.find((e)=>e.examId===id);if(existing&&!canManageExam(u,id))throw new Error('Ujian milik panitia lain.');let ownerId=u.role==='teacher'?u.userId:(input.ownerId||existing?.ownerId||store.teachers[0]?.userId||'');const record:ExamRecord={...input,examId:id,ownerId,ownerName:teacherName(ownerId),tokenRequired:Boolean(input.token)};const idx=store.exams.findIndex((e)=>e.examId===id);if(idx>=0)store.exams[idx]=record;else store.exams.unshift(record);persist();return clone(record);}
  async deleteExam(token:string,examId:string){await delay();const u=userFromToken(token);requireManager(u);if(!canManageExam(u,examId))throw new Error('Tidak diizinkan.');store.exams=store.exams.filter((e)=>e.examId!==examId);delete store.examMappings[examId];store.questions=store.questions.map((q)=>q.examId===examId?{...q,examId:undefined}:q);persist();}
  async duplicateExam(token:string,examId:string){await delay();const u=userFromToken(token);requireManager(u);if(!canManageExam(u,examId))throw new Error('Tidak diizinkan.');const src=store.exams.find((e)=>e.examId===examId)!;const newId=uid('EX');const copy:ExamRecord={...clone(src),examId:newId,title:`${src.title} (Salinan)`,status:'DRAFT',ownerId:u.role==='teacher'?u.userId:src.ownerId,ownerName:u.role==='teacher'?u.name:src.ownerName};store.exams.unshift(copy);store.examMappings[newId]=[...(store.examMappings[examId]||[])];persist();return clone(copy);}
  async getExamQuestionIds(token:string,examId:string){await delay();const u=userFromToken(token);requireManager(u);if(!canManageExam(u,examId))throw new Error('Tidak diizinkan.');return clone(store.examMappings[examId]||[]);}
  async saveExamQuestions(token:string,examId:string,questionIds:string[]){await delay();const u=userFromToken(token);requireManager(u);if(!canManageExam(u,examId))throw new Error('Tidak diizinkan.');const allowed=new Set(store.questions.filter((q)=>u.role==='super_admin'||q.authorId===u.userId).map((q)=>q.questionId));const ids=[...new Set(questionIds)].filter((id)=>allowed.has(id));store.examMappings[examId]=ids;const ex=store.exams.find((e)=>e.examId===examId);if(ex)ex.questionCount=ids.length;persist();return{questionCount:ids.length};}
  async listQuestionPackages(token:string):Promise<QuestionPackageSummary[]>{await delay();const u=userFromToken(token);requireManager(u);const map=new Map<string,QuestionPackageSummary>();store.questions.filter((q)=>u.role==='super_admin'||q.authorId===u.userId).forEach((q)=>{const category=String(q.category||'').trim(),packageName=String(q.packageName||'').trim();if(!packageName)return;const key=`${category}__${packageName}`;const row=map.get(key)||{category:category||'Tanpa Kategori',packageName,questionCount:0,publishedCount:0,subject:q.tag||q.topicCode||''};row.questionCount++;if(['PUBLISHED','ACTIVE'].includes(String(q.status)))row.publishedCount=(row.publishedCount||0)+1;map.set(key,row);});return [...map.values()].sort((a,b)=>a.category.localeCompare(b.category)||a.packageName.localeCompare(b.packageName));}
  async applyQuestionPackage(token:string,examId:string,category:string,packageName:string){await delay();const u=userFromToken(token);requireManager(u);if(!canManageExam(u,examId))throw new Error('Tidak diizinkan.');const ids=store.questions.filter((q)=>(u.role==='super_admin'||q.authorId===u.userId)&&String(q.packageName||'').trim()===String(packageName||'').trim()&&(String(category||'').trim()?(String(q.category||'').trim()||'Tanpa Kategori')===String(category||'').trim():true)&&['PUBLISHED','ACTIVE'].includes(String(q.status))).map((q)=>q.questionId);if(!ids.length)throw new Error('Paket soal tidak memiliki soal PUBLISHED.');store.examMappings[examId]=ids;const ex=store.exams.find((e)=>e.examId===examId);if(ex)ex.questionCount=ids.length;persist();return{questionCount:ids.length};}
  async listQuestions(token:string,examId?:string){await delay();const u=userFromToken(token);if(u.role==='student') throw new Error('Anda tidak memiliki izin.');let rows=store.questions.filter((q)=>u.role==='validator'?store.assignments.some(a=>a.questionId===q.questionId&&a.validatorId===u.userId):u.role==='super_admin'||q.authorId===u.userId||(!q.authorId&&q.examId&&canManageExam(u,q.examId))).map(q=>({...q, validationStatus: (store.validations || {})[q.questionId]?.status || 'PENDING', validationNote: (store.validations || {})[q.questionId]?.note || ''}));if(examId){const mapped=new Set(store.examMappings[examId]||[]);rows=rows.filter((q)=>mapped.has(q.questionId));}return clone(rows);}
  async listValidators(token:string){await delay();const u=userFromToken(token);if(!['super_admin','teacher','validator'].includes(u.role))throw new Error('Tidak memiliki izin.');return clone(store.validators);}
  async listAssignments(token:string){await delay();const u=userFromToken(token);if(u.role==='student')throw new Error('Tidak memiliki izin.');const rows=store.assignments.filter(a=>u.role==='validator'?a.validatorId===u.userId:(u.role==='teacher'?a.authorId===u.userId:true));return clone(rows);}
  async saveAssignments(token:string,questionIds:string[],validatorIds:string[]){await delay();const u=userFromToken(token);if(u.role!=='super_admin'&&u.role!=='teacher')throw new Error('Hanya Super Admin atau Panitia yang dapat menugaskan soal.');const validators=store.validators.filter(v=>validatorIds.includes(v.userId));const questions=store.questions.filter(q=>questionIds.includes(q.questionId)&&(u.role==='super_admin'||q.authorId===u.userId));for(const q of questions){for(const v of validators){const old=store.assignments.find(a=>a.questionId===q.questionId&&a.validatorId===v.userId);if(!old)store.assignments.push({assignmentId:uid('AS'),questionId:q.questionId,questionCode:q.code,questionText:q.questionText,validatorId:v.userId,validatorName:v.name,status:'PENDING',authorId:q.authorId,authorName:q.authorName});}}persist();return this.listAssignments(token);}
  async validateQuestion(token:string,questionId:string,decision:'APPROVED'|'REVISION_REQUIRED'|'REJECTED',note=''){await delay();const u=userFromToken(token);if(u.role!=='validator'&&u.role!=='super_admin')throw new Error('Hanya Validator yang dapat memvalidasi soal.');if(decision!=='APPROVED'&&!note.trim())throw new Error('Catatan wajib diisi untuk keputusan ini.');const q=store.questions.find(x=>x.questionId===questionId);if(!q)throw new Error('Soal tidak ditemukan.');const now=new Date().toISOString();const mine=store.assignments.find(a=>a.questionId===questionId&&a.validatorId===u.userId);if(mine){mine.status=decision;mine.note=note.trim();mine.updatedAt=now;}const approved=store.assignments.some(a=>a.questionId===questionId&&a.status==='APPROVED');const overall=approved?'APPROVED':decision; (store.validations || (store.validations = {}))[questionId]={status:overall,note:note.trim(),updatedAt:now};persist();return clone({...q,validationStatus:overall,validationNote:note.trim()});}
  async saveQuestion(token:string,input:AdminQuestionInput){
    await delay();
    const u=userFromToken(token);
    if(u.role==='student') throw new Error('Anda tidak memiliki izin.');
    if(input.simulationEnabled&&!isSimulationUrlAllowed(input.simulationUrl||''))throw new Error('Gunakan URL HTTPS dari GitHub Pages, Vercel, atau Netlify untuk simulasi.');
    const id=input.questionId||uid('Q');
    const existing=store.questions.find((q)=>q.questionId===id);
    if(existing&&u.role!=='super_admin'&&u.role!=='validator'&&existing.authorId!==u.userId)throw new Error('Soal milik pengguna lain.');

    // AdminQuestionInput.questionText is intentionally optional because imports may
    // provide rich HTML only. QuestionRecord, however, always exposes plain text to
    // the exam engine, so normalize it here instead of spreading `undefined` into
    // a required property.
    const questionText=(input.questionText||plainText(input.questionHtml||'')).trim();
    const questionHtml=(input.questionHtml||input.questionText||'').trim();
    const record:QuestionRecord={
      ...input,
      questionId:id,
      authorId:existing?.authorId||u.userId,
      authorName:existing?.authorName||u.name,
      examId:existing?.examId||undefined,
      questionText,
      questionHtml,
      interactionData: input.questionType==='MATCHING' ? (input.interactionData||{left:[],right:[]}) : undefined,
    };
    const substantiveEdit=Boolean(existing && ((input.questionHtml||'').trim() !== (existing.questionHtml||'').trim() || input.optionA !== existing.optionA || input.optionB !== existing.optionB || input.optionC !== existing.optionC || input.optionD !== existing.optionD || input.optionE !== existing.optionE || input.correctAnswers !== existing.correctAnswers || input.explanation !== existing.explanation || input.simulationEnabled !== existing.simulationEnabled || input.simulationUrl !== existing.simulationUrl || input.simulationTitle !== existing.simulationTitle || input.simulationDescription !== existing.simulationDescription || input.simulationAspectRatio !== existing.simulationAspectRatio));
    const idx=store.questions.findIndex((q)=>q.questionId===id);
    if(idx>=0)store.questions[idx]=record;else store.questions.unshift(record);
    if(substantiveEdit){store.assignments.filter(a=>a.questionId===id).forEach(a=>{a.status='PENDING';a.note='';a.updatedAt=new Date().toISOString()});delete store.validations[id];}
    if(input.examId){
      const mapped=store.examMappings[input.examId]||[];
      if(!mapped.includes(id))store.examMappings[input.examId]=[...mapped,id];
    }
    persist();
    return clone(record);
  }
  async deleteQuestion(token:string,questionId:string){await delay();const u=userFromToken(token);requireManager(u);const q=store.questions.find((x)=>x.questionId===questionId);if(!q||(u.role!=='super_admin'&&q.authorId!==u.userId))throw new Error('Tidak diizinkan.');store.questions=store.questions.filter((x)=>x.questionId!==questionId);Object.keys(store.examMappings).forEach((id)=>store.examMappings[id]=store.examMappings[id].filter((qid)=>qid!==questionId));persist();}
  async importQuestionsCsv(token:string,csvText:string){await delay();const u=userFromToken(token);requireManager(u);const lines=csvText.trim().split(/\r?\n/),headers=parseCsvLine(lines.shift()||'').map((x)=>x.trim()),errors:string[]=[];let imported=0;for(let i=0;i<lines.length;i++){if(!lines[i].trim())continue;const vals=parseCsvLine(lines[i]).map((v)=>v.trim());const row=Object.fromEntries(headers.map((h,j)=>[h,vals[j]||'']));try{if(row.examId&&!canManageExam(u,row.examId))throw new Error('ujian tujuan tidak diizinkan');const existingByCode=row.code?store.questions.find((q)=>String(q.code||'').toLowerCase()===String(row.code||'').toLowerCase()&&(u.role==='super_admin'||q.authorId===u.userId)):undefined;await this.saveQuestion(token,{questionId:existingByCode?.questionId,examId:row.examId||undefined,code:row.code||'',stimulusOrder:Number(row.stimulusOrder||1),topicCode:row.topicCode||'',blueprintCode:row.blueprintCode||'',questionText:row.questionText||row.questionHtml||'',questionHtml:row.questionHtml||row.questionText||'',explanation:row.explanation||'',optionA:row.optionA||'',optionB:row.optionB||'',optionC:row.optionC||'',optionD:row.optionD||'',optionE:row.optionE||'',interactionData:parseInteractionData(row.interactionData||''),correctAnswers:row.correctAnswers||row.correctAnswer||'',score:Number(row.score||row.maxScore||1),maxScore:Number(row.maxScore||row.score||1),questionType:(row.questionType||'SINGLE_CHOICE') as QuestionRecord['questionType'],scoringMode:(row.scoringMode||'EXACT_MATCH') as QuestionRecord['scoringMode'],difficulty:row.difficulty||'Sedang',tag:row.tag||'',category:row.category||'',packageName:row.packageName||'',status:(row.status||'DRAFT') as QuestionRecord['status']});imported++;}catch(error){errors.push(`Baris ${i+2}: ${error instanceof Error?error.message:'gagal'}`);}}persist();return{imported,errors};}
  async uploadQuestionImage(token:string,file:{name:string;mimeType:string;base64:string}):Promise<UploadImageResponse>{await delay();const u=userFromToken(token);requireManager(u);return{fileId:uid('FILE'),imageUrl:`data:${file.mimeType};base64,${file.base64}`,name:file.name};}
  async listStudents(token:string){await delay();const u=userFromToken(token);requireManager(u);return clone(store.students);}
  async saveStudent(token:string,input:AdminStudentInput){await delay();const u=userFromToken(token);requireManager(u);const id=input.userId||uid('S');const record:StudentRecord={userId:id,name:input.name,username:input.username,email:input.email,phone:input.phone,className:input.className,role:'student',status:input.status};const idx=store.students.findIndex((s)=>s.userId===id);if(idx>=0)store.students[idx]=record;else store.students.unshift(record);persist();return clone(record);}
  async deleteStudent(token:string,userId:string){await delay();const u=userFromToken(token);requireManager(u);store.students=store.students.filter((s)=>s.userId!==userId);persist();}
  async importStudents(token:string,rows:ImportStudentRow[],defaultPassword?:string):Promise<ImportStudentsResult>{await delay(180);const u=userFromToken(token);requireManager(u);let created=0,updated=0,skipped=0;const errors:string[]=[];const seen=new Set<string>();for(let i=0;i<rows.length;i++){const row=rows[i],line=i+2,username=String(row.username||'').trim(),name=String(row.name||'').trim(),className=String(row.className||'').trim();if(!name||!username||!className){errors.push(`Baris ${line}: nama, username, dan kelas wajib diisi.`);skipped++;continue;}const key=username.toLowerCase();if(seen.has(key)){errors.push(`Baris ${line}: username ${username} duplikat di file.`);skipped++;continue;}seen.add(key);const existing=store.students.find(s=>s.username.toLowerCase()===key);if(existing){Object.assign(existing,{name,username,className,email:row.email||existing.email,phone:row.phone||existing.phone,status:row.status||'ACTIVE'});updated++;}else{const password=row.password||defaultPassword;if(!password){errors.push(`Baris ${line}: password wajib untuk peserta baru ${username}.`);skipped++;continue;}store.students.unshift({userId:uid('S'),name,username,className,email:row.email,phone:row.phone,role:'student',status:row.status||'ACTIVE'});created++;}}persist();return{created,updated,skipped,errors};}

  async listUsers(token:string){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');return clone([SUPER_ADMIN,...store.teachers,...store.validators,...store.students]);}
  async saveUser(token:string,input:AdminUserInput){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');if(input.role==='super_admin'){return clone({...SUPER_ADMIN,...input,userId:input.userId||SUPER_ADMIN.userId,role:'super_admin'} as User);}if(input.role==='teacher')return this.saveTeacher(token,{userId:input.userId,name:input.name,username:input.username,email:input.email,phone:input.phone,subject:input.subject||'',password:input.password,status:input.status});if(input.role==='validator'){const id=input.userId||uid('V');const record:User={userId:id,name:input.name,username:input.username,email:input.email,phone:input.phone,subject:input.subject||'Fisika',role:'validator',status:input.status};const idx=store.validators.findIndex(v=>v.userId===id);if(idx>=0)store.validators[idx]=record;else store.validators.unshift(record);persist();return clone(record);}return this.saveStudent(token,{userId:input.userId,name:input.name,username:input.username,email:input.email,phone:input.phone,className:input.className||'',password:input.password,status:input.status});}
  async deleteUser(token:string,userId:string){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');if(userId===SUPER_ADMIN.userId)throw new Error('Super Admin demo utama tidak dapat dihapus.');if(store.teachers.some(t=>t.userId===userId))return this.deleteTeacher(token,userId);if(store.validators.some(v=>v.userId===userId)){store.validators=store.validators.filter(v=>v.userId!==userId);persist();return;}return this.deleteStudent(token,userId);}
  async listTeachers(token:string){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');return clone(store.teachers);}
  async saveTeacher(token:string,input:TeacherInput){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');const id=input.userId||uid('T');const record:TeacherRecord={userId:id,name:input.name,username:input.username,email:input.email,phone:input.phone,subject:input.subject,role:'teacher',status:input.status};const idx=store.teachers.findIndex((t)=>t.userId===id);if(idx>=0)store.teachers[idx]=record;else store.teachers.unshift(record);persist();return clone(record);}
  async deleteTeacher(token:string,userId:string){await delay();const u=userFromToken(token);if(u.role!=='super_admin')throw new Error('Hanya Super Admin.');if(store.exams.some((e)=>e.ownerId===userId))throw new Error('Panitia masih memiliki ujian. Nonaktifkan akun atau pindahkan ujian terlebih dahulu.');store.teachers=store.teachers.filter((t)=>t.userId!==userId);persist();}
  async getMonitoring(token:string,examId?:string):Promise<MonitoringRow[]>{await delay();const u=userFromToken(token);requireManager(u);if(!examId)return[];if(!canManageExam(u,examId))throw new Error('Anda tidak memiliki izin.');const ex=store.exams.find((e)=>e.examId===examId);if(!ex)return[];return store.students.filter((st)=>st.status==='ACTIVE'&&st.className===ex.className).map((st)=>{const a=store.attempts.find((x)=>x.studentId===st.userId&&x.examId===examId);return{attemptId:a?.attemptId,studentId:st.userId,studentName:st.name,className:st.className,examId,examTitle:ex.title,status:a?.status||'NOT_STARTED',startedAt:a?.startedAt,lastSyncAt:a?.startedAt,revision:a?.revision||0,submittedAt:a?.submittedAt,focusViolationCount:a?.focusViolationCount||0,warningMessage:a?.lastWarning,warningAt:a?.lastWarningAt,expiresAt:a?.expiresAt};});}
  async setAttemptPaused(token:string,attemptId:string,paused:boolean):Promise<AttemptControl>{await delay();const u=userFromToken(token);requireManager(u);const a=store.attempts.find((x)=>x.attemptId===attemptId);if(!a||!canManageExam(u,a.examId))throw new Error('Pengerjaan tidak ditemukan.');if(paused&&a.status==='IN_PROGRESS'){a.status='PAUSED';a.pauseStartedAt=new Date().toISOString();}else if(!paused&&a.status==='PAUSED'){const delta=Math.max(0,Date.now()-new Date(a.pauseStartedAt||Date.now()).getTime());a.expiresAt=new Date(new Date(a.expiresAt).getTime()+delta).toISOString();a.status='IN_PROGRESS';a.pauseStartedAt='';}persist();return{attemptId:a.attemptId,status:a.status,expiresAt:a.expiresAt,serverTime:new Date().toISOString(),focusViolationCount:a.focusViolationCount||0,warningMessage:a.lastWarning,warningAt:a.lastWarningAt};}
  async warnAttempt(token:string,attemptId:string,message:string){await delay();const u=userFromToken(token);requireManager(u);const a=store.attempts.find((x)=>x.attemptId===attemptId);if(!a||!canManageExam(u,a.examId))throw new Error('Pengerjaan tidak ditemukan.');a.lastWarning=message;a.lastWarningAt=new Date().toISOString();persist();return{attemptId,warningMessage:message,warningAt:a.lastWarningAt};}
  async getAttemptControl(token:string,attemptId:string):Promise<AttemptControl>{await delay(50);const u=userFromToken(token);if(u.role!=='student')throw new Error('Hanya peserta.');const a=store.attempts.find((x)=>x.attemptId===attemptId&&x.studentId===u.userId);if(!a)throw new Error('Pengerjaan tidak ditemukan.');return{attemptId:a.attemptId,status:a.status,expiresAt:a.expiresAt,serverTime:new Date().toISOString(),focusViolationCount:a.focusViolationCount||0,warningMessage:a.lastWarning,warningAt:a.lastWarningAt};}
  async reportFocusViolation(token:string,attemptId:string,count=1){await delay(40);const u=userFromToken(token);if(u.role!=='student')throw new Error('Hanya peserta.');const a=store.attempts.find((x)=>x.attemptId===attemptId&&x.studentId===u.userId);if(!a)throw new Error('Pengerjaan tidak ditemukan.');a.focusViolationCount=(a.focusViolationCount||0)+Math.max(1,count);persist();return{attemptId,focusViolationCount:a.focusViolationCount};}
  async resetAttempt(token:string,attemptId:string){await delay();const u=userFromToken(token);requireManager(u);const attempt=store.attempts.find((a)=>a.attemptId===attemptId);if(!attempt)throw new Error('Pengerjaan tidak ditemukan atau sudah direset.');if(!canManageExam(u,attempt.examId))throw new Error('Anda tidak memiliki izin.');if(!['SUBMITTED','EXPIRED'].includes(attempt.status))throw new Error('Reset hanya tersedia untuk peserta yang sudah selesai mengerjakan.');store.submissions=store.submissions.filter((s)=>s.attemptId!==attemptId);store.attempts=store.attempts.filter((a)=>a.attemptId!==attemptId);persist();return{attemptId,reset:true};}
  async getAdminResults(token:string,examId?:string){await delay();const u=userFromToken(token);requireManager(u);const ids=new Set(visibleExams(u).map((e)=>e.examId));return clone(store.submissions.filter((s)=>ids.has(s.examId)&&(!examId||s.examId===examId)));}
}
