'use client';
import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { Check, ClipboardList, Users } from 'lucide-react';
import { PageHeader, Badge, EmptyState, Skeleton } from '@/components/ui';
import { useSession } from '@/contexts/session-context';
import { getExamApi, type QuestionRecord, type User, type ValidationAssignment } from '@/lib/api';

export function AssignmentManager({ validatorOnly=false }: { validatorOnly?: boolean }) {
 const {session}=useSession(); const [questions,setQuestions]=useState<QuestionRecord[]>([]); const [validators,setValidators]=useState<User[]>([]); const [assignments,setAssignments]=useState<ValidationAssignment[]>([]); const [selectedQuestions,setSelectedQuestions]=useState<string[]>([]); const [selectedValidators,setSelectedValidators]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const load=async()=>{if(!session)return;setLoading(true);try{const a=await getExamApi().listAssignments(session.token);setAssignments(a);if(!validatorOnly){const [q,v]=await Promise.all([getExamApi().listQuestions(session.token),getExamApi().listValidators(session.token)]);setQuestions(q);setValidators(v)}}finally{setLoading(false)}}; useEffect(()=>{load()},[session,validatorOnly]);
 const assignedByQuestion=useMemo(()=>new Map(assignments.map(a=>[a.questionId,a])),[assignments]);
 const toggle=(id:string,setter:Dispatch<SetStateAction<string[]>>)=>setter(xs=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id]);
 const save=async()=>{if(!session||!selectedQuestions.length||!selectedValidators.length)return;setSaving(true);try{await getExamApi().saveAssignments(session.token,selectedQuestions,selectedValidators);setSelectedQuestions([]);setSelectedValidators([]);await load()}finally{setSaving(false)}};
 if(loading)return <Skeleton height={360}/>;
 if(validatorOnly)return <><PageHeader eyebrow="PENUGASAN" title="Soal yang Ditugaskan" description="Daftar soal yang perlu Anda validasi."/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Kode</th><th>Soal</th><th>Panitia</th><th>Status</th></tr></thead><tbody>{assignments.map(a=><tr key={a.assignmentId}><td><strong>{a.questionCode||a.questionId}</strong></td><td>{a.questionText}</td><td>{a.authorName||'-'}</td><td><Badge tone={a.status==='APPROVED'?'success':a.status==='PENDING'?'warning':'neutral'}>{a.status==='PENDING'?'Perlu divalidasi':a.status}</Badge></td></tr>)}</tbody></table>{!assignments.length&&<EmptyState title="Belum ada penugasan" description="Belum ada soal yang ditugaskan kepada Anda."/>}</div></section></>;
 return <><PageHeader eyebrow="PENUGASAN VALIDATOR" title="Penugasan Soal" description="Pilih satu atau beberapa soal, lalu tugaskan kepada satu atau beberapa Validator." action={<button className="button primary" disabled={saving||!selectedQuestions.length||!selectedValidators.length} onClick={save}><Check size={17}/>{saving?'Menyimpan...':'Simpan Penugasan'}</button>}/><div className="assignment-grid"><section className="panel"><div className="assignment-heading"><div><ClipboardList size={19}/><strong>Pilih soal</strong></div><span>{selectedQuestions.length} dipilih</span></div><div className="assignment-list">{questions.map(q=><label className="assignment-row" key={q.questionId}><input type="checkbox" checked={selectedQuestions.includes(q.questionId)} onChange={()=>toggle(q.questionId,setSelectedQuestions)}/><div><strong>{q.code||q.questionId}</strong><small>{q.questionText}</small></div><Badge tone={assignedByQuestion.has(q.questionId)?'primary':'neutral'}>{assignedByQuestion.has(q.questionId)?'Sudah ditugaskan':'Belum'}</Badge></label>)}</div></section><section className="panel"><div className="assignment-heading"><div><Users size={19}/><strong>Pilih Validator</strong></div><span>{selectedValidators.length} dipilih</span></div><div className="assignment-list">{validators.map(v=><label className="assignment-row" key={v.userId}><input type="checkbox" checked={selectedValidators.includes(v.userId)} onChange={()=>toggle(v.userId,setSelectedValidators)}/><div><strong>{v.name}</strong><small>{v.username} · {v.subject||'Fisika'}</small></div></label>)}</div><p className="assignment-help">Jika satu soal ditugaskan kepada beberapa Validator, satu keputusan <b>Valid</b> sudah cukup untuk menetapkan soal sebagai valid.</p></section></div></>;
}
