function getSpreadsheet_() {
  const id = PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');
  if (!id) throw apiError_('SPREADSHEET_ID belum dikonfigurasi. Jalankan setupSainsMasemba().', 'NOT_CONFIGURED');
  return SpreadsheetApp.openById(id);
}
function getSheet_(name) { const sheet=getSpreadsheet_().getSheetByName(name); if(!sheet)throw apiError_('Sheet '+name+' tidak ditemukan.','NOT_CONFIGURED'); return sheet; }
function sheetHeaders_(name){const sheet=getSheet_(name);if(sheet.getLastColumn()<1)return[];return sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(String);}
function rows_(name) { const sheet=getSheet_(name),values=sheet.getDataRange().getValues();if(values.length<2)return[];const headers=values[0].map(String);return values.slice(1).filter(row=>row.some(v=>v!=='')).map((row,index)=>{const obj={_row:index+2};headers.forEach((h,i)=>obj[h]=row[i]);return obj;}); }
function appendObject_(name,obj){const headers=sheetHeaders_(name);getSheet_(name).appendRow(headers.map(h=>obj[h]===undefined?'':obj[h]));return obj;}
function findRowByKey_(name,key,value){return rows_(name).find(row=>String(row[key])===String(value))||null;}
function updateRowByKey_(name,key,value,patch){const sheet=getSheet_(name),data=sheet.getDataRange().getValues();if(!data.length)return null;const headers=data[0].map(String),idx=headers.indexOf(key);if(idx<0)throw apiError_('Kolom key tidak ditemukan.','SCHEMA_ERROR');for(let r=1;r<data.length;r++){if(String(data[r][idx])===String(value)){const next={};headers.forEach((h,i)=>next[h]=patch[h]===undefined?data[r][i]:patch[h]);sheet.getRange(r+1,1,1,headers.length).setValues([headers.map(h=>next[h]===undefined?'':next[h])]);next._row=r+1;return next;}}return null;}
function deleteRowByKey_(name,key,value){const sheet=getSheet_(name),data=sheet.getDataRange().getValues();if(!data.length)return false;const headers=data[0].map(String),idx=headers.indexOf(key);for(let r=data.length-1;r>=1;r--){if(String(data[r][idx])===String(value)){sheet.deleteRow(r+1);return true;}}return false;}
function ensureSheet_(spreadsheet,name,headers){let sheet=spreadsheet.getSheetByName(name);if(!sheet){sheet=spreadsheet.insertSheet(name);sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);}else if(sheet.getLastRow()===0){sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);}else{const existing=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(String);const missing=headers.filter(h=>existing.indexOf(h)<0);if(missing.length)sheet.getRange(1,existing.length+1,1,missing.length).setValues([missing]);}
  const width=sheet.getLastColumn();if(width){sheet.getRange(1,1,1,width).setFontWeight('bold').setBackground('#0B5DB4').setFontColor('#ffffff');sheet.autoResizeColumns(1,width);}return sheet;}
function updateKnownRow_(name,rowObj,patch){if(!rowObj||!rowObj._row)throw apiError_('Referensi row tidak valid.','SCHEMA_ERROR');const headers=sheetHeaders_(name),merged={};headers.forEach(h=>merged[h]=patch[h]===undefined?rowObj[h]:patch[h]);getSheet_(name).getRange(Number(rowObj._row),1,1,headers.length).setValues([headers.map(h=>merged[h]===undefined?'':merged[h])]);merged._row=rowObj._row;return merged;}
